### PR TITLE
Bugfix/tlfv std type list getter refactoring

### PR DESCRIPTION
**Pull request by yevheniyvall**

### CODE REVIEW

**Comment by arnout** [comment]
At first sight, this already looks OK. Is there any reason to keep it as draft?

**Comment by arnout** [comment]
Just two comments:

- Run `tools/docker/clang-format.sh`.
- Refer to the issue #156 in the commit message.

**Review by tomereli — COMMENTED** [review]
I agree with @arnout , this already looks OK - waiting for it to become ready for review

**Comment by tomereli** [comment]
PR name contains "bugfix" but this is not a bugfix, it is refactoring. You should also provide a description to the PR itself (can be a copy of the main commit message).

**Comment by yevheniyvall** [comment]
@tomereli Ok, sure, I will do this after fix code itself.
According to CONTRIBUTING.md:

> We give branches a name following <type>/<subject>. Types are feature for feature development, bugfix for fixing bugs from the issues list, hotfix for small fixes without an issue, and dev/<user> for personal development branches that are not meant for merging.

There is no "refactoring" type. Should I add it into CONTRIBUTING.md?

**Comment by arnout** [comment]
> @tomereli Ok, sure, I will do this after fix code itself.
> According to CONTRIBUTING.md:
> 
> > We give branches a name following /. Types are feature for feature development, bugfix for fixing bugs from the issues list, hotfix for small fixes without an issue, and dev/ for personal development branches that are not meant for merging.
> 
> There is no "refactoring" type. Should I add it into CONTRIBUTING.md?

I think @tomereli was talking about the Pull Request description, not the branch name. The branch name is OK IMO. For the Pull Request, it's nice to put something more extensive. As @tomereli said, it can be a copy of the commit message of the most important commit of the series. In fact, if a PR has only one commit, you'll get that automatically.

Note that this is really not so important, just makes life easier for reviewers if they can see at first glance what this PR is about.

**Pull request closed without merging**
