### PR TITLE
tests: 4.2.1 Multi-AP Ethernet Onboarding and Initialization. #343

### PR DESCRIPTION
**Pull request by VladyslavTupikin**
This test verifies that a MAUT can be onboarded via Ethernet
to a Multi-AP network and initialized.

### CODE REVIEW

**Comment by tomereli** [comment]
I'm not sure this is going in the right direction. We already have the autoconfig and autoconfig renew tests which basically checks onboarding and autoconfiguration.
The only part which is missing to cover all the parts in 4.2.1 is the channel selection, for which we also have a test - so we just need to make sure the channel selection test covers everything defined in the 4.2.1_ETH test.

**Review by tomereli — CHANGES_REQUESTED** [review]
I'm not sure this is going in the right direction. We already have the autoconfig and autoconfig renew tests which basically checks onboarding and autoconfiguration.
The only part which is missing to cover all the parts in 4.2.1 is the channel selection, for which we also have a test - so we just need to make sure the channel selection test covers everything defined in the 4.2.1_ETH test.

**Comment by VladyslavTupikin** [comment]
Pull request closed because function for checking 4.2.1 ETH test flow exist in the python script with name channel_selection.

**Comment by tomereli** [comment]
@VladyslavTupikin please also delete the branch if not needed.

**Pull request closed without merging**
