### PR TITLE
get interfaces info from netfid instead of from cmdline

### PR DESCRIPTION
**Pull request by dangowrt**

### CODE REVIEW

**Comment by dangowrt** [comment]
So this should probably be moved to platform_interfaces replacing most of the existing logic in there and no longer using the global variables
```
static int    interfaces_nr                    = 0;
static char **interfaces_list                  = NULL;
static char **interfaces_list_extended_params  = NULL;
```
Right now interface names are collected and then properties of the interfaces associated with these names are collected. I suggest to drop that entirely and interate through `ubus call network.wireless status` to collect the relevant wireless devices and then add all the _remaining_ bridge-members as well and populate their properties as well (ie. `ubus call network.device status '{"name":"eth0"}'` or even dig through VLAN layer down to physical device as well). Then all the exotic devices-handlers can also be dropped and we end up with simply reading the interfaces and their properties in one step from netifd.

**Comment by arnout** [comment]
> So this should probably be moved to platform_interfaces replacing most of the existing logic in there and no longer using the global variables

That was indeed the plan. Will you work on that or shall I?

**Comment by dangowrt** [comment]
I can work on that today and hopefully finish by tonight (CET/GMT+1).

**Comment by arnout** [comment]
Merged with slight changes (into a separate al_entity_openwrt.c file, to avoid all the ifdeffery).

**Pull request closed without merging**
