### PR TITLE
documentation: Point to confluence iso github

### PR DESCRIPTION
**Pull request by ghost**
I'm disabling the github wiki in favor of confluence, so make sure to link people to the right place.

### CODE REVIEW

**Review by mariomaz — APPROVED** [review]
LGTM

**Review by itayx — APPROVED** [review]
Looks great

**Review by VladyslavTupikin — APPROVED** [review]

**Review by RanRegev — APPROVED** [review]
Maybe it would be a good idea to _keep_ the wiki in github with one page that includes one link: to the confluence.

**Comment by rmelotte** [comment]
@fvbogaert I took the liberty to change your S-O-B line so that mergify can merge it.

**Pull request merged**
