### PR TITLE
tests: add MAP-4.10.3_ETH to passing tests

### PR DESCRIPTION
**Pull request by tomereli**
With the new UCC 10.6.1 and using mediatek controller instead of
broadcomm, we can now pass the following tests:

MAP-4.10.3_ETH_FH24G:netgear-rax40
MAP-4.10.3_ETH_FH5GH:netgear-rax40
MAP-4.10.3_ETH_FH5GL:netgear-rax40

Depends on the following merge requests:
https://git.prpl.dev/prplmesh/wfa-certification/ucc/-/merge_requests/3
https://git.prpl.dev/prplmesh/wfa-certification/easymesh_cert/-/merge_requests/17

Signed-off-by: Tomer Eliyahu <tomer.b.eliyahu@intel.com>

### CODE REVIEW

**Review by rmelotte — APPROVED** [review]
Approving already to make it possible to merge it once the tests pass.

**Review by arnout — APPROVED** [review]

**Comment by rmelotte** [comment]
The tests were failing, and the following was seen in the logs:
```
'status,INVALID,errorCode,invalid param value 'ce:73:85:ec:5e:a0' for param name 'DestALID', destination not found'
```

I rebased the branch on master to include commit b3d785ffbd635cae65f734d5ee2b421bd15f8909 (to allow prplMesh to send messages to other agents when it's told to by the UCC).

**Comment by rmelotte** [comment]
2 variants of the test are passing.
+It looks like the 5GL variant fail at switching channels:+
```
DEBUG 19:20:36:308 <1445739856> son_slave_thread.cpp[4459] --> Received ACK_MESSAGE, mid=7
DEBUG 19:20:36:309 <1999600888> ap_wlan_hal_dwpal.cpp[1244] --> switch channel command: CHAN_SWITCH 5 5180 bandwidth=20 ht
DEBUG 19:20:36:839 <1999600888> base_wlan_hal_dwpal.cpp[501] --> 
cmd failed: CHAN_SWITCH 5 5180 bandwidth=20 ht
DEBUG 19:20:36:840 <1999600888> base_wlan_hal_dwpal.cpp[502] --> 
reply: FAIL

ERROR 19:20:36:841 <1999600888> ap_wlan_hal_dwpal.cpp[1246] --> switch_channel() failed!
ERROR 19:20:36:842 <1999600888> ap_manager_thread.cpp[503] --> Failed to set AP channel!
TRACE 19:20:36:867 <1999600888> ap_wlan_hal_dwpal.cpp[1705] --> process_dwpal_event - opcode: |AP-CSA-FINISHED|
DEBUG 19:20:36:870 <1999600888> ap_wlan_hal_dwpal.cpp[1712] --> <3>AP-CSA-FINISHED wlan2 freq=5180 Channel=36 OperatingChannelBandwidt=20 ExtensionChannel=0 cf1=5180 cf2=0 reason=UNKNOWN dfs_chan=0
INFO 19:20:36:871 <1445739856> son_slave_thread.cpp[1880] --> received ACTION_APMANAGER_HOSTAP_CSA_ERROR_NOTIFICATION
```

EDIT: nevermind, it looks like it still switches channel even though it says it failed.

**Comment by rmelotte** [comment]
The 5GL variant was still using the Broadcom controller. I fixed this, and some other minor things (see https://git.prpl.dev/prplmesh/wfa-certification/easymesh_cert/-/merge_requests/17).

**Pull request merged**
