### PR TITLE
hotfix:test_channel_selection

### PR DESCRIPTION
**Pull request by VladyslavTupikin**
Corrected AL-MAC in channel selection request.

### CODE REVIEW

**Review by tomereli — APPROVED** [review]

**Comment by rmelotte** [comment]
I didn't look into in in details but: how is it possible that the test doesn't fail before this commit?
If sending the test payload to the wrong MAC address doesn't change the test result at all, it sounds like there is something wrong with the test itself.

@VladyslavTupikin any idea?

**Comment by arnout** [comment]
> I didn't look into in in details but: how is it possible that the test doesn't fail before this commit?
> If sending the test payload to the wrong MAC address doesn't change the test result at all, it sounds like there is something wrong with the test itself.

There is something wrong with the test itself. We currently don't check at all if the message is taken into account by the agent, i.e. if it switches channels to one of the channels specified in the message. So a missing message for one of the radios is not noticed.

What this mistake does expose is that we don't detect that there are two conflicting channel preference TLVs. But I don't know if we need to handle that case gracefully anyway. We don't crash, which IMO is sufficient.

**Comment by arnout** [comment]
Oh and BTW I accidentally fixed this while rebasing #1031, so maybe we can close this.

**Comment by VladyslavTupikin** [comment]
Fixed in #1031

**Pull request closed without merging**
