### PR TITLE
Certification: add axepoint and turris omnia

### PR DESCRIPTION
**Pull request by rmelotte**
Adds support for running the certification tests with either the Axepoint or the Turris Omnia.
The list of test job has been taken from the existing wired backaul tests for the rax40.
The wireless backhaul tests will have to be added later. 

Depends on: https://git.prpl.dev/prplmesh/wfa-certification/easymesh_cert/-/merge_requests/20

Fixes https://jira.prplfoundation.org/browse/PPM-221
Fixes https://jira.prplfoundation.org/browse/PPM-222

### CODE REVIEW

**Review by VladyslavTupikin — APPROVED** [review]

**Comment by VladyslavTupikin** [comment]
@rmelotte  Test MAP-4.12.2_ETH failed!

**Review by arnout — APPROVED** [review]
LGTM. Only, we still need to add an axepoint-bhwifi version.

**Review by kantera800 — APPROVED** [review]
approving 
@rmelotte one thing bothers me is that we can't really run both rax40@axepoint in the same test since the device name is identical , do we have an issue/fix for that or we are not planning to support this at all?

**Comment by rmelotte** [comment]
@kantera800 what do you mean "in the same test"?
The device name is not the same: the rax40 uses "netgear-rax40", and the axepoint uses "axepoint".
So if you mention this this in the last commit message it will run the test once with the axepoint and once with the rax40:
MAP-4.12.2:axepoint
MAP-4.12.2:netgear-rax40

**Pull request merged**
