### PR TITLE
[PPM-284] Remove ACTION_CONTROL_SLAVE_JOINED_4ADDR_MODE_NOTIFICATION

### PR DESCRIPTION
**Pull request by VladyslavTupikin**
Need to remove ACTION_CONTROL_SLAVE_JOINED_4ADDR_MODE_NOTIFICATION
message and all related code.

https://jira.prplfoundation.org/browse/PPM-284

### CODE REVIEW

**Review by vitalii-komisarenko — CHANGES_REQUESTED** [review]
1. Commit message header is a big long, I suggest removing ACTION_CONTROL_ from the first line.
2. It would be also nice to include the reason of the removal (something like "because these messages are not used") directly into the commit message.
3. JIRA ID mentioned in the PR needs to be duplicated in the commit message because PRs are not preserved by git.

**Review by vitalii-komisarenko — CHANGES_REQUESTED** [review]
"common: tlvf: Remove SLAVE_JOINED_4ADDR_MODE_NOTIFICATION" is the commit message header I wanted. 
I appologize if my words were confusing.

**Review by vitalii-komisarenko — APPROVED** [review]

**Review by vitalii-komisarenko — APPROVED** [review]

**Review by adam1985d — APPROVED** [review]
looks ok - FYI `PPM-#` where `#` is the PPM number would be enough for the link to issue to work.

**Review by rmelotte — APPROVED** [review]

**Comment by VladyslavTupikin** [comment]
Strange, I do not see this issue on my local PC...

**Pull request merged**
