### PR TITLE
doc: add beerocks_v1_4_Architecture

### PR DESCRIPTION
**Pull request by tomereli**
This document is focused on describing the high-level architecture and flows for BeeRocks core that implements WFA
Multi-AP (EasyMesh) controller & agent including Intel enhancements. The document allows engineers to
understand: high-level architecture, brake down to modules, modules communication, supported features and system
flows.

Signed-off-by: Tomer Eliyahu tomer.b.eliyahu@intel.com

### CODE REVIEW

**Comment by simonbaren** [comment]
I think you should consider changing Beerocks to prplMesh in the file name and inside the file as well

**Review by simonbaren — DISMISSED** [review]
Consider changing Beerocks to prplMesh in the file

**Comment by arnout** [comment]
> Consider changing Beerocks to prplMesh in the file

The plan is to convert the docx into web pages in prplMesh.github.io and do the replacement then. Mirko said he could find someone outside of our team to do that.

**Review by arnout — APPROVED** [review]
Please also add the docx and if possible the uml files and any visio graphs as png.

**Pull request merged**
