### PR TITLE
Bugfix for uninitialized variable usage

### LINKED ISSUE #872: [BUG] agent: Unitialized variable
**Describe the bug** -
The wired_link_state variable is used uninitialized in backhaul_manager_thread.cpp

## Additional context

This gave a compilation error on Econet when using GCC 5.5 and only in Release mode (-O3).

### PR DESCRIPTION
**Pull request by juanschroeder**
This bug is also in master branch.

### CODE REVIEW

**Review by rmelotte — CHANGES_REQUESTED** [review]
Please remove the merge commit from the branch. I'm not sure what the mergify bot would do with it.

Could you also update the commit headline to match more or less what [CONTRIBUTING.md](https://github.com/prplfoundation/prplMesh/blob/master/CONTRIBUTING.md) says, so something like:
`agent: backhaul_fsm_main: fix usage of uninitialized wired_link_state` 
(the guide says to avoid using the word "fix", but as long as it explains what is done in my opinion it's ok)

Last thing, if possible please add to the commit message how you came across the bug, or what the consequences of the bug were (if applicable). 
For example if you noticed that the agent always crashed in a particular way for you because of the undefined behavior, it would be useful to know.

**Comment by tomereli** [comment]
Can this be fixed?

**Review by tomereli — CHANGES_REQUESTED** [review]
Something went seriousely wrong now in this PR, it looks like it reverts a bunch of other PRs. Did you rebase on master before force pushing? Do not use git merge...

**Comment by juanschroeder** [comment]
I updated the commit message and removed the merge. Current commit only has a one line change.

About the merge, I don't know what I did. Maybe I pressed the 'Update branch' button in the web interface.

**Review by tomereli — APPROVED** [review]
Happened to me as well when compiling on Ubuntu 16.04 when building Release.

**Review by morantr — APPROVED** [review]

**Review by rmelotte — APPROVED** [review]

**Pull request merged**
