### PR TITLE
hotfix/Fix VSCODE prplMesh workspace file

### PR DESCRIPTION
**Pull request by morantr**
Some developers and I use VSCODE as our IDE and encountered a problem with the C/CPP extension.
For some reason "go to definition/declaration" did not work properly.
I have found out that if I open the project with the workspace file on "tools/" instead of
"Open Folder" the problem is fixed, but a new problem has shown - The search files (ctrl+P)
was not able to find files that were not recently open.

The solution that fixes it all was to create a new workspace file on the main project folder.
The previous workspace file has been deleted. There were some folder paths that have been
removed since they are no longer exist.

Signed-off-by: Moran Shoeg <moranx.shoeg@intel.com>

### CODE REVIEW

**Comment by vitalybu** [comment]
Why do you need a workspace and not just open the repo as a folder?

**Comment by morantr** [comment]
> Why do you need a workspace and not just open the repo as a folder?

I wrote it on the commit message.

**Comment by vitalybu** [comment]
> > Why do you need a workspace and not just open the repo as a folder?
> 
> I wrote it on the commit message.

It doesn't make sense.
You didn't fix the problem, but found a workaround you think works, but can't explain why...

**Comment by morantr** [comment]
> > > Why do you need a workspace and not just open the repo as a folder?
> > 
> > 
> > I wrote it on the commit message.
> 
> It doesn't make sense.
> You didn't fix the problem, but found a workaround you think works, but can't explain why...

Does it really matter? It allows us to work.
I tried to find why it happens, but I couldn't find why. I assume it is a bug in the extension.

**Comment by vitalybu** [comment]
> Does it really matter? It allows us to work.
> I tried to find why it happens, but I couldn't find why. I assume it is a bug in the extension.

Of course it does. We don't do things we don't understand.
In any case, it works perfectly fine for me, so maybe it's a local configuration issue on your end.

**Review by tomereli — APPROVED** [review]

**Review by itayx — APPROVED** [review]

**Pull request merged**
